apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: my-app
        image: registry.gitlab.com/test-group5525628/my-registry:carnivorous_green_house
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
